In [17]:
import tensorflow as tf

In [25]:
#Multiplication
x_1= tf.constant([[2,3,4],
                  [6,4,3]])
x_2= tf.constant([[2,3],
                  [6,4],
                  [5,6]])
print(x_1.shape,x_2.shape)
tf.linalg.matmul(x_1,x_2,transpose_a=False,transpose_b=False,adjoint_a=False,adjoint_b=False,a_is_sparse=False,b_is_sparse=False,output_type=None,name=None)

(2, 3) (3, 2)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[42, 42],
       [51, 52]])>

In [27]:
print(x_1@x_2)  #Matrix Multiplication

tf.Tensor(
[[42 42]
 [51 52]], shape=(2, 2), dtype=int32)


In [29]:
print(tf.transpose(x_1))

tf.Tensor(
[[2 6]
 [3 4]
 [4 3]], shape=(3, 2), dtype=int32)


In [35]:
#transpose
x_1= tf.constant([[2,3,4],
                  [6,4,3]])
x_2= tf.constant([[2,3],
                  [6,4],
                  [5,6]])
print(x_1.shape,x_2.shape)
tf.linalg.matmul(x_1,x_2,transpose_a=True,transpose_b=True,adjoint_a=False,adjoint_b=False,a_is_sparse=False,b_is_sparse=False,output_type=None,name=None)

(2, 3) (3, 2)


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[22, 36, 46],
       [18, 34, 39],
       [17, 36, 38]])>

In [37]:
print(tf.transpose(x_1)@tf.transpose(x_2))

tf.Tensor(
[[22 36 46]
 [18 34 39]
 [17 36 38]], shape=(3, 3), dtype=int32)


In [43]:
x1= tf.constant([[[1,2,3],[4.9,5,6],[7,8,9]],[[9,8,7],[6,5,4],[3,2,1]]],dtype=tf.float16) #calculate matrix by matrix for mirror index
x2= tf.constant([[[1,2,3],[4.9,5,6],[7,8,9]],[[9,8,7],[6,5,4],[3,2,1]]],dtype=tf.float16)
print(tf.linalg.matmul(x1,x2))

tf.Tensor(
[[[ 31.8  36.   42. ]
  [ 71.4  82.8  98.7]
  [109.2 126.  150. ]]

 [[150.  126.  102. ]
  [ 96.   81.   66. ]
  [ 42.   36.   30. ]]], shape=(2, 3, 3), dtype=float16)


In [49]:
#band_part
x_1= tf.constant([[2,3,4],
                  [6,4,3]])
tf.linalg.band_part(x_1,0,0) #(input,upper,lower)-->output Diagonal
#m--rows, n--columns
#(m-n<=lower) and (n-m<=upper)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 0, 0],
       [0, 4, 0]])>

In [51]:
tf.linalg.band_part(x_1,-1,0) #output--> upper triangular 0

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 0, 0],
       [6, 4, 0]])>

In [55]:
tf.linalg.band_part(x_1,0,-1) #output--> lower tirangular 0

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 3, 4],
       [0, 4, 3]])>

In [57]:
#cross Product
tf.linalg.cross(x1,x2)

<tf.Tensor: shape=(2, 3, 3), dtype=float16, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float16)>

In [85]:
#determinant
x_1 = tf.constant([[2, 3, 4],
                   [6, 4, 3],
                   [2, 3, 4]], dtype=tf.float32)
print(tf.linalg.det(x_1))


tf.Tensor(-0.0, shape=(), dtype=float32)


In [89]:
x_1 = tf.constant([[2, 3, 4],
                   [1, 2, 3],
                   [3, 0, 1]], dtype=tf.float32)

# Compute the determinant to check if it's non-zero-->determinant must be non zero
det = tf.linalg.det(x_1)
print(f"Determinant: {det.numpy()}")  # Non-zero determinant

# Compute the inverse
inv = tf.linalg.inv(x_1)
print("Inverse:")
print(inv)

Determinant: 4.0
Inverse:
tf.Tensor(
[[ 0.5000001  -0.7500001   0.24999997]
 [ 2.0000002  -2.5000002  -0.5000001 ]
 [-1.5000002   2.2500002   0.2500001 ]], shape=(3, 3), dtype=float32)


**inverse x non_inverse same matrix will give Idnentity matrix**

In [102]:
#svd--> s- tensor of singular value, u- left singualar value, v=right sigular value
x_1 = tf.constant([[2, 3, 4],
                   [1, 2, 3],
                   [3, 0, 1]], dtype=tf.float32)
s,u,v=tf.linalg.svd(x_1)
print(s)
print(u)
print(v)

tf.Tensor([6.823836  2.5261471 0.2320454], shape=(3,), dtype=float32)
tf.Tensor(
[[ 0.78602856 -0.18210113  0.5907608 ]
 [ 0.5386413  -0.26719633 -0.7990443 ]
 [ 0.303356    0.94627964 -0.1119368 ]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 0.4426786   0.8738367   0.20110895]
 [ 0.50343657 -0.4278042   0.75068986]
 [ 0.7420157  -0.23106872 -0.6293011 ]], shape=(3, 3), dtype=float32)


**matmul is eihsum gives same output**


***NUMPY***

In [4]:
import numpy as np

In [24]:
#element wise multiplication
a = np.array([[2, 3, 4],
                   [1, 2, 3],
                   [3, 0, 1]])
b = np.array([[2, 3, 4],
                   [1, 2, 3],
                   [3, 0, 1]])
print("Einsum C=:")
print(np.einsum('ij,ij -> ij',a,b)) #for 3d--> batchsize=b,i,j

Einsum C=:
[[ 4  9 16]
 [ 1  4  9]
 [ 9  0  1]]


In [19]:
a.T #transpose

array([[2, 1, 3],
       [3, 2, 0],
       [4, 3, 1]])

***To expand dimention use---> tf.expand_dims(tesor_name,axis=0)***

In [28]:
x_1 = tf.constant([[2, 3, 4],
                   [1, 2, 3],
                   [3, 0, 1]], dtype=tf.float32)
tf.expand_dims(x_1,axis=0)

AttributeError: module 'ml_dtypes' has no attribute 'float8_e3m4'


<tf.Tensor: shape=(1, 3, 3), dtype=float32, numpy=
array([[[2., 3., 4.],
        [1., 2., 3.],
        [3., 0., 1.]]], dtype=float32)>

In [44]:
tf.expand_dims(x_1,axis=1) #axis--> nth dim 0--> means 1st dim...so on 

<tf.Tensor: shape=(3, 1, 3), dtype=float32, numpy=
array([[[2., 3., 4.]],

       [[1., 2., 3.]],

       [[3., 0., 1.]]], dtype=float32)>

In [46]:
x_mod=tf.expand_dims(x_1,axis=2)

***Squeezed--> tf.squeeze(x_mod,axis=0)***

***reshape--> tf.reshape(x_mod,[value] or [value,value])---> to modify the tensor***

***Concat--->tf.concat([t1,t2],axis=0)--->axis 0=> concat in rows***

In [61]:
tensor1 = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])  # Shape: (2, 2, 2)
tensor2 = tf.constant([[[9, 10], [11, 12]], [[13, 14], [15, 16]]])  # Shape: (2, 2, 2)

# Concatenate along axis 0
concat_axis0 = tf.concat([tensor1, tensor2], axis=0)
print("Concatenated along axis 0:\n", concat_axis0.numpy())

# Concatenate along axis 1
concat_axis1 = tf.concat([tensor1, tensor2], axis=1)
print("\nConcatenated along axis 1:\n", concat_axis1.numpy())

# Concatenate along axis 2
concat_axis2 = tf.concat([tensor1, tensor2], axis=2)
print("\nConcatenated along axis 2:\n", concat_axis2.numpy())

Concatenated along axis 0:
 [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]

 [[13 14]
  [15 16]]]

Concatenated along axis 1:
 [[[ 1  2]
  [ 3  4]
  [ 9 10]
  [11 12]]

 [[ 5  6]
  [ 7  8]
  [13 14]
  [15 16]]]

Concatenated along axis 2:
 [[[ 1  2  9 10]
  [ 3  4 11 12]]

 [[ 5  6 13 14]
  [ 7  8 15 16]]]


***tf.stack([t1,t2],axis=)--->adds an extra axis---> combination of concat and expand_dims***

***tf.pad()-->padding***

In [69]:
tensor = tf.constant([[1, 2], [3, 4]])

# Add padding: 1 row before and after, 2 columns before and after
paddings = tf.constant([[1, 1], [2, 2]])   #{row,column}
padded_tensor = tf.pad(tensor, paddings, mode='CONSTANT', constant_values=0)

print("Original Tensor:\n", tensor.numpy())
print("\nPadded Tensor:\n", padded_tensor)

Original Tensor:
 [[1 2]
 [3 4]]

Padded Tensor:
 tf.Tensor(
[[0 0 0 0 0 0]
 [0 0 1 2 0 0]
 [0 0 3 4 0 0]
 [0 0 0 0 0 0]], shape=(4, 6), dtype=int32)


**tf.gather(tensor_name,[index_number]), axis=**

***tf.gather_nd(params, indeices)--> N dimentions of params***