In [13]:
import tensorflow as tf

In [27]:
tensor1 = tf.constant([
    [1, 2, 3], 
    [4, 5, 6],
    [4, 5, 0]])
tensor2 = [
    [7, 8],
    [3],
    [9, 10,3,4,5],
    [2,3]]

print(tensor1)

AttributeError: module 'ml_dtypes' has no attribute 'float8_e3m4'
tf.Tensor(
[[1 2 3]
 [4 5 6]
 [4 5 0]], shape=(3, 3), dtype=int32)


In [37]:
tensor_ragged=tf.ragged.constant(tensor2) #does not need to be ractangular data

In [39]:
print(tensor2)

[[7, 8], [3], [9, 10, 3, 4, 5], [2, 3]]


**Bool mask**

In [44]:
# Aliases for True & False so data and mask line up.
T, F = (True, False)

In [50]:
tf.ragged.boolean_mask(  # Mask a 2D Tensor.
    data=[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    mask=[[T, F, T], [F, F, F], [T, F, F]]).to_list()

[[1, 3], [], [7]]

In [74]:
#row length
print(tf.RaggedTensor.from_row_lengths(
    values=[1, 2, 3, 4, 5, 6],
    row_lengths=[4, 2]))

<tf.RaggedTensor [[1, 2, 3, 4], [5, 6]]>


**rowlimits works kindof same as index wise**

**tf.RaggedTensor.from_row_splits(value= ,
                                 row_splites=)**

In [81]:
dt = tf.constant([[5, 7, 0], [0, 3, 0], [6, 0, 0]])
tf.RaggedTensor.from_tensor(dt)

tf.RaggedTensor.from_tensor(dt, lengths=[1, 0, 3])

<tf.RaggedTensor [[5], [], [6, 0, 0]]>