In [1]:
import tensorflow as tf

In [9]:
tensorSparse= tf.sparse.SparseTensor(
    indices=[[1,1],[3,4]],values=[11,22],dense_shape=[5,6]
)

In [11]:
print(tensorSparse)

SparseTensor(indices=tf.Tensor(
[[1 1]
 [3 4]], shape=(2, 2), dtype=int64), values=tf.Tensor([11 22], shape=(2,), dtype=int32), dense_shape=tf.Tensor([5 6], shape=(2,), dtype=int64))


In [13]:
tf.sparse.to_dense(tensorSparse)

<tf.Tensor: shape=(5, 6), dtype=int32, numpy=
array([[ 0,  0,  0,  0,  0,  0],
       [ 0, 11,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 22,  0],
       [ 0,  0,  0,  0,  0,  0]])>