In [2]:
import tensorflow as tf

In [4]:
tensor_string=tf.constant(['hello', 'this is', 'a string'])
print(tensor_string)

AttributeError: module 'ml_dtypes' has no attribute 'float8_e3m4'
tf.Tensor([b'hello' b'this is' b'a string'], shape=(3,), dtype=string)


In [18]:
string=tf.strings.join(tensor_string, separator=' ')

In [20]:
tf.strings.length(tensor_string)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 7, 8])>

In [22]:
tf.strings.lower(string)

<tf.Tensor: shape=(), dtype=string, numpy=b'hello this is a string'>

In [26]:
tf.strings.upper(string)

<tf.Tensor: shape=(), dtype=string, numpy=b'HELLO THIS IS A STRING'>