In [1]:
import tensorflow as tf

In [7]:
x_abs=tf.constant([-2,2,-22,45])  #canverts all neg value to pos.
tf.abs(x_abs)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 2,  2, 22, 45])>

In [17]:
x_complex=tf.constant([-2.5-4.3j])  #sqrt(x^2+y^2)
tf.abs(x_complex)

<tf.Tensor: shape=(1,), dtype=float64, numpy=array([4.97393205])>

In [15]:
tf.sqrt((-2.5)**2+(4.3)**2)

<tf.Tensor: shape=(), dtype=float32, numpy=4.973931789398193>

In [25]:
x_1=tf.constant([-2,2,-22,45]) 
x_2=tf.constant([-2,2,-22,0]) 
print(tf.add(x_1,x_2))
print(tf.divide(x_1,x_2))
print(tf.math.divide_no_nan(x_1,x_2)) #no_nan--> gives output without inf.



tf.Tensor([ -4   4 -44  45], shape=(4,), dtype=int32)
tf.Tensor([ 1.  1.  1. inf], shape=(4,), dtype=float64)
tf.Tensor([1. 1. 1. 0.], shape=(4,), dtype=float64)


In [37]:
x_1=tf.constant([[-2,2,-22,45],[2,3,6,7]]) 
x_2=tf.constant([-2,2,-22,0]) 
print(tf.add(x_1,x_2))

tf.Tensor(
[[ -4   4 -44  45]
 [  0   5 -16   7]], shape=(2, 4), dtype=int32)


**Tf automacally strach the array to do any math operation**

In [42]:
x_1=tf.constant([-2,2,-22,45]) 
x_2=tf.constant([-3,4,-72,0])
tf.math.minimum(x_1,x_2)

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ -3,   2, -72,   0])>

In [82]:
x_argmax=tf.constant([
    [1,2,3],
    [4,5,6],
    [3,8,9]
])
print(x_argmax.shape)
print(tf.math.argmax(x_argmax),0)  #return the index of the maximum value--> 0--> compare values in each columns
print(tf.math.argmin(x_argmax),1)  #return the index of the minimum value--> 1--> campare values in each rows


(3, 3)
tf.Tensor([1 2 2], shape=(3,), dtype=int64) 0
tf.Tensor([0 0 0], shape=(3,), dtype=int64) 1


In [84]:
x_2=tf.constant([200,222,-222,330]) 
print(tf.math.argmax(x_2))  #return the index of the maximum value

tf.Tensor(3, shape=(), dtype=int64)


In [88]:
#equal campares tensors
x_1=tf.constant([-2,2,-22,45]) 
x_2=tf.constant([-2,4,-72,0])
tf.math.equal(x_1,x_2)

<tf.Tensor: shape=(4,), dtype=bool, numpy=array([ True, False, False, False])>

In [92]:
#pow
x=tf.constant([[2,6],[3,4]])  #2^3,6^2,3^1,4^3
y=tf.constant([[3,2],[1,3]])
tf.pow(x,y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 8, 36],
       [ 3, 64]])>

In [114]:
#reduce sum
x_argmax=tf.constant([
    [1,2,3],
    [4,5,6],
    [3,8,9]
])
print(tf.math.reduce_sum(x_argmax,axis=0,keepdims=False,name=None))
print(tf.math.reduce_max(x_argmax,axis=1,keepdims=False,name=None))
print(tf.math.reduce_min(x_argmax,axis=0,keepdims=False,name=None))
print(tf.math.reduce_mean(x_argmax,axis=0,keepdims=False,name=None))


tf.Tensor([ 8 15 18], shape=(3,), dtype=int32)
tf.Tensor([3 6 9], shape=(3,), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([2 5 6], shape=(3,), dtype=int32)


In [116]:
x_argmax = tf.constant([[1.0, 2.0, 3.0],
                        [4.0, 5.0, 6.0],
                        [7.0, 8.0, 9.0]])

print(tf.math.reduce_std(x_argmax, axis=0))

tf.Tensor([2.4494898 2.4494898 2.4494898], shape=(3,), dtype=float32)


In [120]:
#top_k funtion
tf.math.top_k(x_argmax,k=2) #2nd matrix returns the index, default value of k is 1-->values are sorted.

TopKV2(values=<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[3., 2.],
       [6., 5.],
       [9., 8.]], dtype=float32)>, indices=<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[2, 1],
       [2, 1],
       [2, 1]])>)