In [1]:
import tensorflow as tf

In [5]:
tensor_zero_d =tf.constant(4)
print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [37]:
tensor_one_d= tf.constant([2,0,-3.7,4])
print(tensor_one_d)

tf.Tensor([ 2.   0.  -3.7  4. ], shape=(4,), dtype=float32)


In [39]:
casted_tensor_one_d=tf.cast(tensor_one_d, dtype=tf.int16)  #converted float to int
print(casted_tensor_one_d)

tf.Tensor([ 2  0 -3  4], shape=(4,), dtype=int16)


In [41]:
casted_tensor_one_d=tf.cast(tensor_one_d, dtype=tf.bool)  #converted float to int
print(casted_tensor_one_d)

tf.Tensor([ True False  True  True], shape=(4,), dtype=bool)


In [15]:
tensor_two_d=tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(tensor_two_d)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [43]:
tensor_bool=tf.constant([True,True,False])
print(tensor_bool)

tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [33]:
tensor_three_d= tf.constant([[[1,2,3],[4.9,5,6],[7,8,9]],[[9,8,7],[6,5,4],[3,2,1]]],dtype=tf.float16)
print(tensor_three_d)

tf.Tensor(
[[[1.  2.  3. ]
  [4.9 5.  6. ]
  [7.  8.  9. ]]

 [[9.  8.  7. ]
  [6.  5.  4. ]
  [3.  2.  1. ]]], shape=(2, 3, 3), dtype=float16)


In [31]:
print(tensor_three_d.shape)

(2, 3, 3)


In [23]:
tensor_four_d=tf.constant([[[[1,2,3],[4,5,6],[7,8,9]],[[9,8,7],[6,5,4],[3,2,1]]],[[[1,2,3],[4,5,6],[7,8,9]],[[9,8,7],[6,5,4],[3,2,1]]],[[[1,2,3],[4,5,6],[7,8,9]],[[9,8,7],[6,5,4],[3,2,1]]]])
print(tensor_four_d)

tf.Tensor(
[[[[1 2 3]
   [4 5 6]
   [7 8 9]]

  [[9 8 7]
   [6 5 4]
   [3 2 1]]]


 [[[1 2 3]
   [4 5 6]
   [7 8 9]]

  [[9 8 7]
   [6 5 4]
   [3 2 1]]]


 [[[1 2 3]
   [4 5 6]
   [7 8 9]]

  [[9 8 7]
   [6 5 4]
   [3 2 1]]]], shape=(3, 2, 3, 3), dtype=int32)


**String**

In [54]:
tensor_string =tf.constant(['Hello, This code is to practice tensor dtypes and variables','hi'])
print(tensor_string)

tf.Tensor([b'Hello, This code is to practice tensor dtypes and variables' b'hi'], shape=(2,), dtype=string)


**Convert numpy array into Tensor**

In [57]:
import numpy as np

In [59]:
np_array=np.array([1,2,3])
np_array

array([1, 2, 3])

In [61]:
converted_to_tensor = tf.convert_to_tensor(np_array)
print(converted_to_tensor)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)


**Eye method-->Construct Identity matrix**

In [93]:
#Construct Identity matrix 
eye_tensor=tf.eye(
    num_rows=5,
    num_columns=None,
    batch_shape=[5,],  #means three 5x5
    dtype=tf.dtypes.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]
  [0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 1.]]], shape=(5, 5, 5), dtype=float32)


**fill method**

In [124]:
fill_tensor=tf.fill([2,5,3],9,name=None) #creates matrix

**Ones method--> all value will be one**

In [120]:
ones_tensor=tf.ones(
    [2,5,3],
    dtype=tf.dtypes.float32,
    name=None
)
print(ones_tensor)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]], shape=(2, 5, 3), dtype=float32)


In [130]:
ones_like=tf.ones_like(fill_tensor)
print(ones_like)

tf.Tensor(
[[[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]], shape=(2, 5, 3), dtype=int32)


**Zeros Method**

In [135]:
tf.zeros(
    [2,5,3],                  #input type,datatype,name
    dtype=tf.dtypes.float32,
    name=None
)

<tf.Tensor: shape=(2, 5, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

**Rank Method**

In [146]:
t= tf.constant([[1,2,3],[4.9,5,6],[7,8,9]],dtype=tf.float16)
tf.rank(t)  #returns dimention of an array

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [150]:
tf.size(t) #size of an array

<tf.Tensor: shape=(), dtype=int32, numpy=9>

***Create Random tensors***

In [179]:
random_tensor=tf.random.normal(  #normal distribution
    [3,2],
    mean=100.0,     #mean--> values will be generated around this mean. 
    stddev=5.0,
    dtype=tf.dtypes.float32,
    seed=None,
    name=None
)
print(random_tensor)

tf.Tensor(
[[105.22321  104.77537 ]
 [103.46165   98.912895]
 [ 99.23858   99.61612 ]], shape=(3, 2), dtype=float32)


In [189]:
uniform_tensor=tf.random.uniform(  #uniform distribution
    [3,2],
    minval=80,
    maxval=100,
    dtype=tf.dtypes.float32,
    seed=None ,
    name=None
)
print(uniform_tensor)

tf.Tensor(
[[83.17148 83.25168]
 [88.19665 83.90588]
 [85.29795 87.60572]], shape=(3, 2), dtype=float32)
