In [2]:
import tensorflow as tf

In [36]:
tensor_indexed=tf.constant([2,43,2,1,4,5,6,7])
print(tensor_indexed)

tf.Tensor([ 2 43  2  1  4  5  6  7], shape=(8,), dtype=int32)


In [10]:
tf.size(tensor_indexed)

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [24]:
print(tensor_indexed[1:4])

tf.Tensor([43  2  1], shape=(3,), dtype=int32)


In [28]:
print(tensor_indexed[-4::2])

tf.Tensor([4 6], shape=(2,), dtype=int32)


In [38]:
print(tensor_indexed[2:-2])

tf.Tensor([2 1 4 5], shape=(4,), dtype=int32)


In [57]:
minindex=tensor_indexed[0]

print(tensor_indexed[minindex:])

tf.Tensor([2 1 4 5 6 7], shape=(6,), dtype=int32)


In [40]:
tensor_two_d=tf.constant([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(tensor_two_d)

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [42]:
print(tensor_two_d[0:3,0:2])

tf.Tensor(
[[1 2]
 [4 5]
 [7 8]], shape=(3, 2), dtype=int32)


In [44]:
print(tensor_two_d[0:3,:])

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


In [46]:
print(tensor_two_d[0:3,...])

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)


**For 3d we need 3 comma**